export const UPDATE_EMPLOYEES = "UPDATE_EMPLOYEES"

export const UPDATE_DEPARTMENTS = "UPDATE_DEPARTMENTS"

export const NEW_EMPLOYEES = "NEW_EMPLOYEES"

export const NEW_DEPARTMENTS = "NEW_DEPARTMENTS"

export const DELETE_EMPLOYEES = "DELETE_EMPLOYEES"

export const DELETE_DEPARTMENTS = "DELETE_DEPARTMENTS"

export const GET_EMPLOYEES = "GET_EMPLOYEES"

export const GET_DEPARTMENTS = "GET_DEPARTMENTS"
